# 配置真实数据源
dataSources:
  # 配置第 1 个数据源
  ds0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://47.113.118.139:3306/ds0
    username: root
    password: 123456
  # 配置第 2 个数据源
  ds1: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://47.113.118.139:3306/ds1
    username: root
    password: 123456
  # 影子库
  ds-shadow0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://47.113.118.139:3306/ds-shadow0
    username: root
    password: 123456
  ds-shadow1: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://47.113.118.139:3306/ds-shadow1
    username: root
    password: 123456

rules:
  # 配置分片规则
  - !SHARDING
    tables:
      # 配置 t_order 表规则
      t_order:
        actualDataNodes: ds${0..1}.t_order${0..1}
        # 配置分库策略
        databaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: database_inline
        # 配置分表策略
        tableStrategy:
          # 标准分表策略（和强制路由只能二选一）
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: table_inline
          # 强制路由
          #hint:
          # shardingAlgorithmName: com.sjdemo.config.HintOrderAlgorithm

      t_order_item:
        actualDataNodes: ds${0..1}.t_order_item${0..1}
        # 配置分库策略
        databaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: database_inline
        # 配置分表策略
        tableStrategy:
          # 标准分表策略（和强制路由只能二选一）
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: table_inline
    # 配置分片算法
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds${user_id % 2}
      table_inline:
        type: INLINE
        props:
          algorithm-expression: t_order${order_id % 2}
    bindingTables:
      - t_order,t_order_item


  - !SHADOW
    column: shadow
    sourceDataSourceNames:
      - ds0
      - ds1
      # ...
    shadowDataSourceNames:
      - ds-shadow0
      - ds-shadow1
props:
  sql-show: true


